### ISSUE TITLE
difference values becomes of type numpy array if feature values is of type list

### ISSUE THREAD

**Issue by Ali-Flt** [Telecommunication-Telemedia-Assessment/quat#3]
In `quat/visual/base_features.py` in line 102 there is
```
elif type(v1) == list:
    res["diff"] = np.array(v1) - np.array(v2)
```
this way the `res["diff"]` value may become a numpy array and result in errors in case you need to dump the result in a json file.
I think this change will resolve the issue (although I'm not sure if it's the best solution or whether it'll break anything else)
```
elif type(v1) == list:
    res["diff"] = (np.array(v1) - np.array(v2)).tolist()
```

**Comment by stg7** [comment]
I included your suggestion, looks valid
